# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
permalink: /:year/:month/:title

# Setup
title:            Douglas C. Wu
tagline:          ''
description:      'From molecular biology to computation'
url:              ""
baseurl:          ""

author:
  name:           'Douglas C. Wu'
  twitter:        'wckdouglas'
  github:         'wckdouglas'   
  gmail:          'wckdouglas'
  googleScholar:  'avA3c5MAAAAJ&hl'
  linkedin:       'wckdouglas'
  orcid:          '0000-0001-6179-3110'  

paginate:         5

include: [_pages]

analytics :
    provider : google
    google :
    tracking_id : 'UA-61925302-1'

# Default extension for new posts and pages
post_ext: md
page_ext: html
# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true
# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft
